version: '3.8'
 
services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    container_name: gitlab
    restart: always
    hostname: gitlab.local
    shm_size: '512m'
    ports:
      - "8084:8084"
      - "2222:22"
    volumes:
      - gitlab-config:/etc/gitlab
      - gitlab-logs:/var/log/gitlab
      - gitlab-data:/var/opt/gitlab
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://localhost:8084'
        gitlab_rails['initial_root_password'] = "G1tl@bP@ssw0rd2025!"
  registry:
    image: registry:2
    container_name: registry
    ports:
      - "8085:5000"
    volumes:
      - registry-data:/var/lib/registry
 
volumes:
  gitlab-config:
  gitlab-logs:
  gitlab-data:
  registry-data:
 